[build]
  publish = "dist"
  command = "gridsome build"

[[redirects]]
  from = "/80g"
  to = "/14TFoundation_80g.pdf"
  status = 200 
  force = true

[[redirects]]
  from = "/checkout/*"
  # to = "/checkout/_order_id.html"
  status = 200
  force = true
