import { GoogleSpreadsheet } from 'google-spreadsheet'

export async function sheetInit(sheetId: string) {
  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  const doc = new GoogleSpreadsheet(sheetId);

  console.log({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SHEETS_SERVICE_ACCOUNT_EMAIL,
    firebase: process.env.FIREBASE_ADMIN_PRIVATE_KEY,
    private_key: process.env.GOOGLE_SHEETS_PRIVATE_KEY.split("\\n").join("\n"),
  })
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SHEETS_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_SHEETS_PRIVATE_KEY.split("\\n").join("\n"),
  });

  return doc
}

export async function addToSheet(doc, data) {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  console.log(data)
  await doc.loadInfo(); // loads document properties and worksheets
  const sheet = doc.sheetsByIndex[0]

  console.log(doc.title, sheet.title);
  const larryRow = await sheet.addRow(data);
}
